# Generated by Django 5.2 on 2025-06-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["deadline"]},
        ),
        migrations.AddField(
            model_name="worker",
            name="completed_tasks",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
