# Generated by Django 5.2 on 2025-06-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_task_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="completed_tasks",
        ),
    ]
